apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc-prod
  annotations:
    harness.io/primary-service: "true"
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc-stage
  annotations:
    harness.io/stage-service: "true"
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
